name: Publish Docker Image to AWS ECR Public

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    environment: certified-builder-py
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # ECR Public só está disponível em us-east-1
          audience: sts.amazonaws.com

      - name: Login to Amazon ECR Public
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/${{ secrets.ECR_REGISTRY_ALIAS }}
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest public.ecr.aws/${{ secrets.ECR_REGISTRY_ALIAS }}/${{ secrets.ECR_REPOSITORY }}:latest
      
      - name: Push Docker image
        run: |
          docker push public.ecr.aws/${{ secrets.ECR_REGISTRY_ALIAS }}/${{ secrets.ECR_REPOSITORY }}:latest
      
      - name: Complete
        run: |
          echo "Docker image has been pushed to AWS ECR Public"

