name: Continuous Integration -Testing - Certified Builder Py
on:
  pull_request:
    branches:
      - main

jobs:
 test:
    name: Continuous Integration - Testing - Certified Builder Py
    runs-on: ubuntu-latest
    environment: certified-builder-py
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.X'
      
      - name: Install dependencies with pip
        run: |
          python -m pip install --upgrade pip
      
      - name: Install libs for testing
        run: |
          pip install -r requirements.txt
      - name: Run tests unit - Testing - Certified Builder Py
        run: |
          pytest   